---
abstract: 'a collection of statistics modules in Perl Data Language, with a quick-start guide for non-PDL people.'
author:
  - 'Maggie J. Xiong  <maggiexyz users.sourceforge.net>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PDL-Stats
no_index:
  directory:
    - t
    - inc
requires:
  PDL: v2.4.4
  Test::More: 0
version: v0.6.4
